songs = {-5 : "A Spoonful of Sugar",
        -4: "A to Z",
        -3 : "ALGORITHM",
        -2 : "Astrogazer",
        -1 : "AWAKE",
        0: " ",
        1: "BLSTR",
        2: "Breathe The Air",
        3: "Butterfly",
        4: "Circle Of Life",
        5: "CONGA",
        6: "Dance Dance Revolution",
        7: "Dead Heat",
        8: "DIVE",
        9: "DROP OUT",
        10: "Electronic or Treat!",
        11: "END OF THE CENTURY",
        12: "Ev'rybody Wants To Be A Cat",
        13: "FOLLOW ME",
        14: "Hanabi",
        15: "Healing Vision",
        16: "Illegal Function Call",
        17: "IRON HEART",
        18: "Neverland",
        19: "New Century",
        20: "Out of focus",
        21: "RISING FIRE HAWK",
        22: "Skywalking",
        23: "Star Trail",
        24: "The World Ends Now",
        25: "Voltississimo"
}
print(songs[int(input())])
