zero = str(int(False))
one = str(int(True))
two = str(int(True + True))
three = str(int(True + True + True))
four = str(int(True + True + True + True))
five = str(int(True + True + True + True + True))
six = str(int(True + True + True + True + True + True))
seven = str(int(True + True + True + True + True + True + True))
eight = str(int(True + True + True + True + True + True + True + True))
nine = str(int(True + True + True + True + True + True + True + True + True))
# print(zero, one, two, three, four, five, six, seven, eight, nine)
print(chr(int(seven + two)) + chr(int(one + zero + one))
      + chr(int(one + zero + eight)) + chr(int(one + zero + eight))
      + chr(int(one + one + one)) + chr(int(four + four))
      + chr(int(three + two)) + chr(int(eight + seven))
      + chr(int(one + one + one)) + chr(int(one + one + four))
      + chr(int(one + zero + eight)) + chr(int(one + zero + zero))
      + chr(int(three + three)))
